# 初始化商店插件
{{ if .Values.init.plugin.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "bkci.names.fullname" . }}-init-plugin
  labels: {{- include "bkci.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: init-plugin
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels: {{- include "bkci.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: init-plugin
    spec:
      containers:
        - name: init-plugin
          image: {{ include "common.images.image" ( dict "imageRoot" .Values.backendImage "global" $) }}
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          workingDir: /data/workspace/
          command:
            - "/bin/bash"
            - "-c"
            - |
              until curl -s "http://{{ include "bkci.names.fullname" . }}-store.{{ .Release.Namespace }}.svc.cluster.local" > nohup
              do 
                echo "waiting for {{ include "bkci.names.fullname" . }}-store";
                sleep 2;
              done
              echo "{{ include "bkci.names.fullname" . }}-store is available";
              {{ range .Values.init.plugin.atoms }}
              atom_url={{ .url }}
              atom_code={{ .code }}
              atom_file=${atom_code}.zip
              curl -s $atom_url -o $atom_file -L
              if [ $? -eq 0 ]; then
                curl "http://{{ include "bkci.names.fullname" $ }}-store.{{ $.Release.Namespace }}.svc.cluster.local/api/op/pipeline/atom/deploy" -H "X-DEVOPS-UID: admin" -F atomCode=$atom_code -F upload=@$atom_file
              fi
              {{ end }}
      restartPolicy: OnFailure
{{- end -}}
