package com.tencent.metrics.constant

const val BK_REPO_CODECC_AVG_SCORE = "repo_codecc_avg_score"
const val BK_RESOLVED_DEFECT_NUM = "resolved_defect_num"
const val BK_QUALITY_PIPELINE_INTERCEPTION_NUM = "quality_pipeline_interception_num"
const val BK_QUALITY_PIPELINE_EXECUTE_NUM = "quality_pipeline_execute_num"
const val BK_TURBO_SAVE_TIME = "turbo_save_time"

const val BK_PIPELINE_NAME = "pipelineName"
const val BK_STATISTICS_TIME = "statistics_time"
const val BK_AVG_COST_TIME = "avgCostTime"
const val BK_ATOM_CODE = "atomCode"
const val BK_ATOM_NAME = "atomName"
const val BK_SUCCESS_RATE = "successRate"
const val BK_TOTAL_EXECUTE_COUNT = "totalExecuteCount"
const val BK_FAIL_EXECUTE_COUNT = "fail_execute_count"
const val BK_TOTAL_AVG_COST_TIME = "total_avg_cost_time"
const val BK_FAIL_AVG_COST_TIME = "fail_avg_cost_time"
const val BK_PIPELINE_ID = "pipelineId"
const val BK_ERROR_TYPE = "errorType"
const val BK_ERROR_NAME = "errorMsg"
const val BK_CLASSIFY_CODE = "classifyCode"
const val BK_SUCESS_EXECUTE_COUNT = "successExecuteCount"
const val BK_ERROR_CODE = "errorCode"
const val BK_ERROR_MSG = "error_msg"
const val BK_START_USER = "startUser"
const val BK_START_TIME = "startTime"
const val BK_END_TIME = "endTime"
const val BK_BUILD_ID = "buildId"
const val BK_BUILD_NUM = "buildNum"

const val BK_ERROR_COUNT_SUM = "error_count_sum"
const val BK_ERROR_COUNT = "error_count"
const val BK_TOTAL_EXECUTE_COUNT_SUM = "totalExecuteCountSum"
const val BK_SUCESS_EXECUTE_COUNT_SUM = "successExecuteCountSum"
const val BK_TOTAL_AVG_COST_TIME_SUM = "total_avg_cost_time_sum"

const val BK_QUERY_COUNT_MAX = 10000

const val BK_ATOM_CODE_FIELD_NAME = "插件"
const val BK_CLASSIFY_CODE_FIELD_NAME = "类型"
const val BK_SUCCESS_RATE_FIELD_NAME = "成功率"
const val BK_AVG_COST_TIME_FIELD_NAME = "平均耗时"
const val BK_TOTAL_EXECUTE_COUNT_FIELD_NAME = "执行次数"
const val BK_SUCESS_EXECUTE_COUNT_FIELD_NAME = "成功执行次数"